// <auto-generated />
using HomePage.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomePage.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20221004200751_AzureDeployment")]
    partial class AzureDeployment
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HomePage.Models.StudentModel", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            FirstName = "Morgan",
                            Grade = "A-",
                            LastName = "Christensen"
                        },
                        new
                        {
                            StudentId = 2,
                            FirstName = "Adam",
                            Grade = "B+",
                            LastName = "Warlock"
                        },
                        new
                        {
                            StudentId = 3,
                            FirstName = "Daniel",
                            Grade = "C",
                            LastName = "Thrasher"
                        },
                        new
                        {
                            StudentId = 4,
                            FirstName = "John",
                            Grade = "B-",
                            LastName = "Snow"
                        },
                        new
                        {
                            StudentId = 5,
                            FirstName = "Christine",
                            Grade = "A",
                            LastName = "Adams"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
